### ISSUE TITLE
Unable to deploy a template with Okta::Application::Application

### ISSUE THREAD

**Issue by ericzbeard** [aws-ia/cloudformation-okta-resource-providers#31]
CloudFormation error:

```
Resource handler returned message: 
"Error: Resource of type 'Okta::Application::Application' with identifier 'id' was not found." 
(RequestToken: b625823c-10ae-bb77-a80f-2209eeb14184, HandlerErrorCode: NotFound)
```

Template:

```yaml
Resources:

  MyApp:
    Type: Okta::Application::Application
    Properties:
      Settings:
        App:
          Url: http://something.example.com
          AuthURL: https://auth.example.com
          SiteURL: https://myurl.com
      Accessibility:
        ErrorRedirectUrl: https://r.example.com
        SelfService: false
      Name: test-app-1
      Label: test-label
      SignOnMode: SECURE_PASSWORD_STORE
```

Seems like this should work. Contract testing passes with this input:

```json
{
  "Settings": {
    "App": {
      "Url": "https://myurl.com",
      "AuthURL": "https://muauthurl.com",
      "SiteURL": "https://myurl.com"
    }
  },
  "Accessibility": {
    "ErrorRedirectUrl": "https://myerrorurl.com",
    "SelfService": false
  },
  "Name": "test_app",
  "Label": "test-label-1",
  "SignOnMode": "SECURE_PASSWORD_STORE"
}

```
